package aoc2022;

import java.util.List;
import java.util.stream.Collectors;

public class Nap02 {
    public static void main(String[] args) {
        List<Jatek> jatekok = jatekokBeolvasasa();
        System.out.println(megoldas1(jatekok));
        System.out.println(megoldas2(jatekok));
    }

    private static List<Jatek> jatekokBeolvasasa() {
        return STRING_INPUT.lines().map(sor -> new Jatek(sor.split(" "))).collect(Collectors.toList());
    }

    private enum KOPAPIROLLO {
        KO(1), PAPIR(2), OLLO(3);

        final int value;

        KOPAPIROLLO(int value) {
            this.value = value;
        }
    }

    private static int enPontjaimSzama(KOPAPIROLLO en, KOPAPIROLLO ellenfel) {
        if (en == ellenfel) {
            return 3 + en.value;
        } else {
            if (isLegyozi(en, ellenfel)) {
                return 6 + en.value;
            } else {
                return en.value;
            }
        }
    }

    private static boolean isLegyozi(KOPAPIROLLO en, KOPAPIROLLO ellenfel) {
        if (en == KOPAPIROLLO.KO) {
            return ellenfel == KOPAPIROLLO.OLLO;
        } else if (en == KOPAPIROLLO.PAPIR) {
            return ellenfel == KOPAPIROLLO.KO;
        } else {
            return ellenfel == KOPAPIROLLO.PAPIR;
        }
    }

    private static class Jatek {

        private final String ellenfel;

        private final String en;

        Jatek(String[] split) {
            this.ellenfel = split[0];
            this.en = split[1];
        }

        KOPAPIROLLO ellenfelKoPapirOllo() {
            return switch (ellenfel) {
                case "A" -> KOPAPIROLLO.KO;
                case "B" -> KOPAPIROLLO.PAPIR;
                case "C" -> KOPAPIROLLO.OLLO;
                default -> throw new IllegalArgumentException("Nem értelmezett betű '" + ellenfel + "'");
            };
        }

        KOPAPIROLLO enKoPapirOllo() {
            return switch (en) {
                case "Y" -> KOPAPIROLLO.PAPIR;
                case "X" -> KOPAPIROLLO.KO;
                case "Z" -> KOPAPIROLLO.OLLO;
                default -> throw new IllegalArgumentException("Nem értelmezett betű '" + en + "'");
            };
        }

        KOPAPIROLLO getEnKoPapirOlloErtek() {
            return kivalaszt(ellenfelKoPapirOllo(), en);
        }
    }

    private static int megoldas1(List<Jatek> jatekok) {
        return jatekok.stream().mapToInt(jatek -> enPontjaimSzama(jatek.enKoPapirOllo(), jatek.ellenfelKoPapirOllo())).sum();
    }

    private static int megoldas2(List<Jatek> jatekok) {
        return jatekok.stream().mapToInt(jatek -> enPontjaimSzama(jatek.getEnKoPapirOlloErtek(), jatek.ellenfelKoPapirOllo())).sum();
    }

    private static KOPAPIROLLO kivalaszt(KOPAPIROLLO ellenfel, String betu) {
        return switch (betu) {
            case "Y" -> ellenfel;
            case "X" -> switch (ellenfel) {
                case PAPIR -> KOPAPIROLLO.KO;
                case KO -> KOPAPIROLLO.OLLO;
                case OLLO -> KOPAPIROLLO.PAPIR;
            };
            case "Z" -> switch (ellenfel) {
                case PAPIR -> KOPAPIROLLO.OLLO;
                case KO -> KOPAPIROLLO.PAPIR;
                case OLLO -> KOPAPIROLLO.KO;
            };
            default -> throw new IllegalStateException("Ismeretlen betű: '" + betu + "'");
        };
    }

    private static final String STRING_INPUT = """
            C X
            C X
            A Y
            C X
            B Y
            A X
            A Z
            B Y
            C Z
            C Z
            B X
            C Z
            B Y
            C Z
            B Y
            A Z
            B Y
            C X
            C X
            C X
            B X
            C Z
            C X
            C Z
            C X
            A Y
            B Y
            B Z
            A X
            C X
            C Z
            C Z
            A Z
            B Y
            C Z
            C X
            C X
            C Z
            B Y
            C Z
            C Z
            C X
            B X
            B X
            A Y
            C Z
            C Z
            B Y
            B Y
            C Z
            C X
            A Z
            C X
            C Z
            C Z
            B X
            C Z
            C Z
            B Y
            A Y
            B X
            C X
            C X
            C Z
            C X
            A Y
            C X
            C Z
            A Z
            B Y
            C Z
            C X
            C X
            C Z
            C Z
            C Z
            A Z
            C Z
            A Z
            A Z
            C X
            B Y
            C X
            C X
            A Z
            C X
            A Y
            C Z
            C Z
            A Y
            A Z
            C Z
            C Z
            A Y
            C Z
            C Y
            B Y
            B Y
            A Z
            A Y
            C Z
            C Z
            A Z
            C Z
            A Y
            B Z
            C X
            C Z
            C X
            B Y
            C Z
            C X
            B Y
            B X
            A Y
            C Z
            C Z
            C Z
            B Z
            A Y
            C Z
            C Z
            C X
            C Z
            C X
            A Y
            C Z
            C Z
            C X
            B Y
            B X
            B Y
            C Z
            C X
            B X
            C Z
            C Z
            A Y
            C Z
            A Z
            A Y
            C Z
            A Y
            C X
            A Y
            C Y
            A Z
            C X
            C X
            B Y
            B Y
            A Y
            A Z
            C Z
            C X
            C Z
            A Y
            B Y
            A Y
            B X
            C Z
            C Z
            A Z
            A Y
            C X
            C X
            C X
            A Z
            B Y
            C Z
            C Z
            C Z
            C X
            B Z
            C Z
            C Z
            B Z
            C Z
            A Z
            B Y
            A Y
            C Z
            B Y
            B X
            B X
            C X
            C Z
            A X
            C Z
            C X
            C X
            C X
            C X
            C X
            B Y
            C X
            C X
            A Y
            A Y
            C Z
            C Z
            B X
            C Z
            C Z
            C Z
            C Z
            A Z
            C Z
            A Z
            B Y
            B Y
            C Z
            B Y
            C Z
            C Z
            C Z
            C X
            B Y
            B Y
            C Z
            A Z
            C Z
            C X
            B Y
            C Z
            A Z
            C Z
            C X
            C Z
            C Z
            C X
            C X
            B Z
            A Y
            B X
            C Z
            B Y
            C X
            C X
            C Z
            C Z
            B X
            B X
            B Y
            A X
            C X
            A Z
            A Z
            C Z
            B Y
            C Z
            A Z
            B X
            C X
            B Y
            A Z
            C X
            A X
            A Z
            B Y
            B X
            B Y
            A Y
            C Z
            C Z
            B X
            C Z
            C X
            B Y
            C Z
            C Z
            A Y
            B Y
            A Z
            A Y
            C X
            C X
            C Z
            A Z
            C Z
            B Z
            A Z
            A Y
            C X
            C Z
            C X
            B Z
            C Z
            B Y
            A Y
            B X
            A Y
            C Z
            A Y
            C Z
            C X
            B Y
            C X
            A Y
            A Z
            C Z
            B Y
            C X
            A Y
            C X
            C Z
            C X
            B Y
            C X
            C Z
            C Z
            A Z
            B Y
            C X
            B X
            A Z
            C X
            C X
            A Y
            B X
            C X
            A Z
            C Z
            C Z
            C Z
            B Y
            A Y
            C X
            C Z
            C Z
            A Z
            C Z
            A Y
            C X
            C X
            C X
            A Z
            B Y
            C Z
            A Y
            C Z
            C Z
            C X
            C Z
            A Z
            C Z
            B Y
            C X
            C X
            C Z
            B Z
            B Y
            C X
            C X
            A Y
            A Z
            A Z
            A X
            C X
            A Y
            B Y
            A Y
            A Z
            B Y
            B Y
            A Y
            B Y
            C X
            A Z
            B X
            C Z
            A Z
            B X
            A Y
            B X
            B Y
            A Y
            A X
            C Z
            B Z
            B X
            B Z
            C Z
            C X
            B X
            B Y
            A Y
            B Y
            B Y
            B Y
            A Z
            A Y
            B X
            A Y
            C X
            B Y
            B X
            B Y
            C X
            A Y
            C X
            A Y
            C Z
            C Z
            A Z
            C Z
            C X
            C X
            A Z
            C X
            C X
            C X
            A Y
            A Z
            A Z
            C Z
            B X
            C X
            C X
            C Z
            A Y
            C X
            C X
            B X
            C Z
            C Z
            C X
            B Z
            C X
            C X
            C Z
            A Y
            C X
            A Z
            C Z
            C X
            B X
            B Y
            C X
            C Z
            C X
            C Z
            A Z
            C Z
            C X
            C Z
            C Z
            A Z
            B X
            C X
            C Z
            C X
            C X
            C Z
            C X
            C Z
            A Z
            A Z
            A Z
            C Z
            C X
            A Z
            C Z
            C Z
            C Z
            A Z
            B Y
            C X
            B Y
            C X
            C Z
            B Y
            C X
            C X
            A Z
            A Z
            C X
            C Z
            C X
            C Z
            A Z
            A Y
            C Z
            C Z
            A Y
            B Y
            B Y
            C Z
            B Y
            B X
            B Z
            A Y
            A Z
            C X
            B Y
            B Z
            B Y
            B Z
            C Z
            B Y
            C Z
            C Z
            B Y
            B X
            B Z
            C X
            A Z
            C X
            C X
            C X
            A Z
            C Z
            A Z
            C Z
            A Y
            C Y
            B Y
            A Z
            B Y
            C Z
            A Z
            A Y
            B X
            C X
            C X
            C X
            C Z
            C X
            B X
            C Z
            A Y
            C Z
            A X
            B Y
            B Z
            C Z
            B Y
            C Z
            B X
            B Y
            C Z
            B X
            A Z
            B X
            B Y
            A Y
            B Z
            C X
            C Z
            A Z
            A Y
            A Z
            C X
            C Z
            B Z
            A Z
            A Z
            C X
            C Z
            C X
            C X
            A Z
            C X
            C X
            C X
            B X
            A Y
            B Y
            B X
            B Y
            C Z
            B Y
            B Z
            C Z
            C X
            B Y
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            A Z
            A Z
            A Z
            C X
            C Z
            B Y
            C Z
            C Z
            C Z
            C Z
            C X
            C X
            A Z
            B Y
            A Z
            B Z
            C X
            C X
            C Z
            C Z
            C X
            A Y
            C X
            A Y
            C Z
            A Z
            C Z
            B X
            C Z
            C Z
            C X
            C X
            C Z
            B Z
            A Y
            B X
            A Y
            B Y
            A Y
            A Z
            A Z
            C Z
            B X
            C Z
            C X
            C Z
            C Z
            A Z
            C X
            A Y
            C X
            A Z
            C Z
            C X
            C Z
            A Z
            C X
            C X
            C X
            C X
            B X
            B Y
            C X
            C Z
            C Z
            C Z
            C Z
            A Z
            A Z
            A Y
            C Z
            C X
            C Z
            C Z
            C Z
            A Y
            C X
            A Z
            C Y
            A Z
            C Z
            C X
            A Y
            C Z
            C X
            C X
            A Z
            B Y
            C Z
            A Z
            C Z
            C Z
            C Z
            B Y
            C X
            C X
            A X
            A Y
            C Z
            A Z
            C Z
            B Y
            C X
            B X
            C X
            C X
            A Y
            C Z
            C Z
            C Z
            C X
            A Z
            B Y
            A Y
            B Z
            B Z
            B X
            A Z
            B X
            B X
            A Z
            A Z
            C Y
            B Y
            C Z
            A X
            C Z
            B X
            C Z
            A Y
            A Y
            C Z
            C Z
            A Z
            B Y
            C Z
            C Z
            C Z
            C X
            A Y
            C X
            B Y
            B Y
            C X
            C Z
            C X
            B X
            A Y
            A Y
            C Z
            C Z
            C Z
            C Z
            C Z
            B X
            C Z
            A Y
            B X
            A Y
            A Z
            C Z
            C X
            B Y
            B Y
            C Z
            C Z
            C Z
            B Y
            C X
            B Y
            A Y
            B X
            C Z
            C Z
            A Y
            C X
            C Z
            A Y
            C X
            C X
            A Z
            C Z
            B X
            A Z
            B Y
            C Z
            A Z
            B X
            C Z
            B Y
            C Z
            B Y
            C X
            C Z
            B X
            C X
            B Y
            C X
            A Y
            C Z
            C Z
            C X
            B Y
            C X
            C Z
            C X
            C Z
            A Z
            A Y
            C X
            C Z
            C Z
            A Z
            C X
            B Z
            A Z
            B Y
            C X
            A Z
            C Z
            B Y
            C X
            C X
            C Z
            C Z
            B Y
            A Z
            C Z
            C X
            C Z
            A Z
            C X
            A Z
            C Z
            C X
            C X
            C Z
            B X
            C Z
            C Z
            C Z
            B Y
            A X
            B Y
            C X
            A Z
            B X
            A Z
            C Z
            C X
            C Z
            C Z
            B Y
            B X
            C Z
            B Z
            B Y
            B X
            C X
            C X
            C X
            C Z
            B Y
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            C X
            C Z
            A Y
            C X
            B X
            A Y
            C X
            C X
            C Z
            C Z
            C X
            B X
            B Y
            B Y
            C Z
            B X
            C X
            C X
            C Z
            C Z
            A Y
            C Z
            A Y
            C Z
            C Z
            B Y
            A Z
            B X
            B X
            C Z
            C Z
            A Y
            A Y
            C Z
            C Z
            C X
            A Y
            A Y
            C Z
            A Z
            C X
            B Z
            A Y
            C X
            B Z
            A Y
            C X
            B Y
            C X
            C X
            C Z
            A X
            C Y
            A Y
            B Z
            B Y
            A X
            B Y
            A Z
            C Z
            C X
            C X
            C X
            C Y
            B Y
            C Z
            A Z
            C X
            C X
            C Z
            C Z
            C X
            C Z
            B Y
            C Z
            C X
            B Y
            A Z
            C X
            B Y
            C Z
            C X
            B Y
            A Z
            B X
            C Z
            B X
            B X
            C Z
            C Z
            C X
            B Y
            A Y
            B X
            B X
            A Y
            B Y
            B Y
            B X
            A Z
            A Y
            C Z
            B Y
            C Z
            A Z
            C Z
            C X
            A Z
            C X
            C Z
            C X
            B Y
            C X
            A Z
            B X
            C Z
            C X
            C X
            B Y
            A Y
            C Z
            C X
            A Y
            A X
            C Z
            B Y
            B X
            C X
            C X
            C X
            C Z
            A Z
            B Y
            A Y
            B Y
            B X
            B Y
            B Y
            A Z
            B Y
            B Y
            B Y
            C Z
            C X
            A Z
            A X
            B Z
            C X
            C X
            C X
            C X
            C Z
            A Z
            B Y
            A Z
            B Y
            C X
            A Z
            A Y
            C Z
            C X
            B X
            A Z
            B Y
            C Z
            A Z
            C X
            A Z
            A Y
            B Y
            C Z
            B Y
            C X
            A Z
            A Z
            A X
            C Z
            C X
            A Y
            B Y
            B X
            C Z
            A Z
            C X
            B X
            B Y
            A Z
            C X
            B Y
            C X
            C Z
            C Z
            B Y
            A Z
            A Y
            C X
            B Y
            C X
            C X
            C Z
            C Z
            C X
            A X
            C X
            A Z
            C Z
            B X
            B X
            C X
            B X
            B Y
            C X
            C X
            A Y
            B Y
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            A Z
            B X
            C X
            B Y
            B Y
            C X
            C Z
            A Z
            C X
            C Z
            C Z
            C X
            A Z
            C Z
            A Z
            C Z
            A Y
            C X
            C X
            B Y
            C X
            C Z
            B X
            A Y
            C Z
            C X
            B Y
            B X
            A Y
            C X
            A Z
            C Z
            C X
            C X
            A Y
            B Y
            C Z
            B Z
            C Z
            C X
            B Y
            C Z
            C X
            A Y
            C X
            C Z
            C X
            C X
            B X
            C X
            B Y
            C X
            C Z
            C X
            B X
            B X
            C Z
            A Y
            C Z
            C Y
            B X
            A Z
            C X
            A Z
            B Z
            A Y
            C Z
            C Z
            A Z
            B Z
            A Z
            C X
            C Z
            C Z
            A Z
            A Y
            C Z
            C X
            A Y
            B Y
            B X
            A Z
            A Y
            C X
            B X
            A Y
            C Z
            B Y
            C X
            C X
            C X
            B X
            A Z
            B Y
            B Y
            A Z
            C X
            B X
            B X
            A Y
            C Z
            C X
            C X
            A Y
            C X
            C X
            C Z
            C X
            A Y
            B Y
            C Z
            A Z
            C Z
            A Z
            A Z
            A Y
            C X
            C X
            C X
            A Y
            A Y
            B Y
            B Z
            A Z
            C X
            C Z
            C X
            C Z
            B X
            C X
            C X
            B X
            C Z
            C X
            B Y
            B X
            C Z
            A Z
            C Z
            B Y
            C Z
            C Z
            B X
            A Y
            B Y
            A Z
            B Y
            C X
            C X
            A Z
            C Z
            C X
            C Z
            C X
            A Z
            C X
            A Z
            C X
            A Y
            A Z
            C X
            C Z
            B Y
            C Z
            A Z
            C Y
            B Z
            B Y
            A Z
            C Z
            A X
            A Z
            C Z
            C X
            C X
            A Y
            C Z
            C X
            C Z
            C Z
            C Z
            B Y
            C Z
            C X
            C Z
            B Y
            C Z
            B Y
            C Z
            C Z
            C Z
            C Z
            C Z
            B Y
            C Z
            B Y
            A Y
            C X
            B Y
            A Y
            C X
            A Z
            A Y
            C Z
            B Y
            C Z
            C X
            A Y
            B Y
            C X
            C X
            C X
            A Y
            A Z
            B X
            B X
            B X
            B Y
            C Z
            B Y
            C Z
            C Z
            B Y
            A X
            C X
            A Y
            C Z
            B Y
            B Y
            C Z
            C Z
            C X
            C Z
            C Z
            B Y
            C Z
            C X
            A Y
            A Z
            C X
            B Z
            C X
            B Y
            C Z
            C X
            A Y
            A Z
            C Z
            C X
            C Z
            C X
            C X
            C X
            C X
            C Z
            C X
            B Y
            A Y
            C X
            C Z
            A Z
            B Y
            C Z
            C X
            C Z
            B Y
            A Z
            A Y
            A Y
            B Y
            B Y
            A Z
            B X
            A Y
            C X
            C X
            A Y
            C X
            A Y
            B Y
            C Z
            A X
            B X
            A Y
            A Z
            C Z
            B X
            C Z
            B Y
            C X
            B Y
            C Z
            A Z
            A Y
            C X
            C Z
            B X
            B Y
            C Z
            C Z
            A Z
            C Z
            B Z
            C X
            C X
            C Z
            C Z
            C Z
            C X
            C X
            C Z
            B Y
            C Z
            B Z
            C X
            A Y
            C Z
            B Y
            C X
            A Y
            C Z
            B X
            C Z
            A Z
            C Z
            C X
            A Y
            A Y
            A Y
            C Z
            C Z
            A Y
            A X
            C Z
            C Z
            C X
            C Z
            A Z
            A Z
            C Z
            C X
            C Z
            B Y
            A Y
            B Z
            B Y
            C X
            C Z
            C X
            B X
            B Y
            C X
            C X
            C X
            A Z
            A Y
            C X
            C Z
            C X
            B Y
            C Z
            B X
            C Z
            B Y
            A Z
            C X
            B Y
            C X
            B X
            A Z
            C X
            B Y
            A Y
            C Z
            C X
            A Y
            C X
            B Y
            B X
            C Z
            C X
            C X
            C Z
            C X
            C X
            A Y
            A X
            C Z
            C Z
            C Z
            B Y
            C Z
            A Z
            B X
            C Z
            C X
            C X
            A Y
            A Z
            B Y
            B Y
            C Z
            C Z
            A Y
            A Z
            A Z
            C Z
            B Y
            B Y
            C Z
            B Y
            C X
            C X
            C Z
            A Z
            C X
            C X
            B Y
            B Y
            C Z
            B Y
            C Z
            C Z
            C Z
            C Z
            C X
            C Z
            B Y
            C Z
            C Z
            B X
            C Z
            C Z
            C X
            B Y
            C Z
            A Z
            A Z
            A Z
            C X
            B Y
            C Z
            A Y
            B X
            C X
            C X
            A X
            A Y
            B X
            C Z
            C X
            C Z
            C Z
            B Y
            C Z
            C Z
            B Z
            C Z
            C Z
            B X
            A Y
            C X
            A Z
            B Y
            A Z
            C X
            B X
            B X
            C Z
            A X
            B Z
            A Z
            B Y
            C X
            C Z
            B Z
            C X
            B X
            C Z
            A Z
            B X
            C Z
            C Z
            A Z
            A Y
            C Z
            C Z
            B X
            A Z
            C Z
            B Y
            B Y
            C Z
            B Y
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            C X
            A Y
            C Z
            C Z
            C X
            C Z
            B Y
            B X
            B Y
            A Z
            C Z
            B Y
            B X
            C Z
            B X
            C Y
            C X
            B Y
            C Z
            B Y
            A Z
            B Y
            C X
            C Z
            B X
            C Z
            A Y
            C Z
            B X
            A Z
            A Y
            B Y
            C Z
            A Y
            B Y
            C X
            A Z
            A Y
            C Z
            C Z
            A Y
            B X
            C X
            B Y
            A Y
            C X
            B X
            C X
            C Z
            C Z
            B Y
            A Z
            B Y
            A Z
            A Y
            A Z
            B X
            A Y
            C X
            B Y
            C Z
            C Z
            A Z
            C Z
            C Z
            C X
            C Z
            C Z
            B Y
            A Z
            C X
            A Y
            C Z
            A X
            A Z
            C Z
            B Y
            C X
            C Y
            A Y
            B X
            B Y
            C Z
            C Z
            B X
            B X
            C Y
            B Y
            B X
            C X
            C Z
            A Z
            C Z
            A Z
            C Z
            C Z
            A Z
            B X
            C Z
            C X
            C Z
            B Y
            B X
            A Z
            C Z
            B X
            C Z
            B Z
            C Z
            B Y
            B Y
            C Z
            B Y
            A Y
            A Z
            A Z
            C X
            A X
            C X
            C Z
            C Z
            A Y
            C Z
            C Z
            C Z
            A Y
            B X
            C Z
            C X
            B X
            C X
            C X
            B Y
            C Z
            B X
            C X
            B Y
            A Y
            C Z
            C X
            C X
            A Z
            B Y
            C Z
            B Y
            C Z
            B Z
            B Y
            B Y
            A Y
            B Y
            B Y
            A X
            A Y
            C Z
            C X
            B X
            C Z
            C X
            C X
            B Y
            C Z
            C Z
            B Y
            A Y
            B Y
            C Z
            C X
            C Z
            C Z
            C X
            A Y
            A Y
            C Z
            A Y
            C X
            C Z
            A Z
            A Z
            C Z
            B Y
            A X
            A X
            B X
            A Z
            C X
            C X
            C X
            C X
            A Z
            A Z
            C X
            B X
            B Y
            C X
            B Y
            B Z
            A Z
            A Y
            C X
            B Y
            B Y
            C Z
            B X
            B X
            C Z
            B Y
            C Z
            C Z
            B Y
            C Z
            C X
            C Z
            B Y
            C X
            C Z
            C Z
            C X
            B X
            C Z
            C X
            C X
            C Y
            C Z
            B Y
            C X
            C X
            A Y
            C X
            C X
            C Z
            C X
            C Z
            C Z
            C Z
            A X
            C Z
            C Y
            C Z
            C Z
            C Z
            C Z
            A X
            C Z
            B X
            C Z
            C X
            B Y
            C X
            A Z
            C Z
            C X
            B Y
            B Y
            A Z
            A Y
            C X
            A Z
            C Z
            C Z
            A Y
            A Z
            A X
            C Z
            A Z
            C Z
            C Z
            C Z
            A Z
            A Y
            A Z
            A Z
            A Y
            A Y
            C X
            A Y
            A Y
            C Z
            C Z
            C Z
            B X
            C X
            C Z
            B X
            C Z
            C Z
            C Z
            C Z
            C Z
            B Y
            C Z
            B Y
            C Z
            C X
            A Z
            C Z
            B X
            B Y
            C X
            B Y
            C X
            C X
            A Y
            C Z
            C X
            C X
            C Z
            C X
            C X
            C Z
            B Y
            B X
            C X
            B X
            B Y
            C X
            A Z
            B Y
            A Z
            B Y
            A Z
            A Y
            C Z
            C Z
            C X
            B Y
            A Y
            A Y
            C X
            B Y
            C X
            A Z
            A Z
            C X
            A X
            C X
            A Z
            C X
            C Z
            C X
            A Y
            C X
            B Y
            B Y
            C X
            A Z
            C Z
            C Z
            B X
            C Z
            C Z
            A Y
            C Z
            B Y
            A Z
            A X
            C Z
            C X
            B Y
            A Z
            C X
            B X
            A Z
            A Z
            C Z
            A Z
            C Z
            C Z
            A X
            C X
            A Z
            C X
            A Y
            B Y
            C Z
            B Y
            B X
            C Z
            A X
            B Z
            A Z
            A Z
            C Z
            A Z
            C Z
            A Z
            C X
            C X
            C X
            C X
            A Z
            C Z
            C X
            B Y
            A Z
            B Y
            A Y
            C Z
            A Z
            C X
            C Z
            B Y
            C X
            A Y
            B X
            A Y
            B X
            B Y
            C Z
            A Y
            B Y
            A Y
            B Y
            C Z
            C X
            C X
            C X
            C Z
            B Y
            C Z
            B X
            C X
            A Y
            A X
            B Y
            A Z
            C Z
            A Y
            A Z
            C X
            B Y
            A Z
            C Z
            C X
            C Y
            C X
            A Z
            A Y
            C X
            A Y
            C X
            C X
            A Z
            B Y
            C Z
            C X
            B X
            B Y
            A Z
            A Z
            B X
            B Y
            C X
            B Y
            C Z
            B Y
            C Y
            B Y
            B X
            B Y
            A Y
            B Y
            C Z
            B X
            B Y
            C Z
            A Z
            C Z
            B X
            A Y
            B X
            C Z
            B Y
            A Y
            C Z
            C Z
            C Y
            C Z
            A Y
            C X
            A Y
            C Z
            C Z
            C Z
            C Z
            C Z
            C X
            C Z
            C Z
            B Y
            C X
            C Z
            B X
            C X
            C Z
            C X
            A Z
            C X
            C X
            C Z
            C X
            C X
            C Z
            A Z
            B X
            B Y
            C Z
            A Z
            C X
            B X
            B Y
            C Z
            C Z
            A Y
            C X
            C Z
            C X
            C Z
            B Y
            C X
            C Z
            C X
            C X
            C Z
            C X
            B X
            C X
            C Z
            A Y
            A Y
            A Y
            C Z
            C Z
            B X
            C X
            A Z
            C Z
            C X
            C Z
            B X
            C Z
            B Z
            C X
            A Y
            C Z
            A Y
            C X
            B Y
            B Y
            A Z
            C Z
            C Z
            C Z
            A Z
            C X
            A Y
            C Z
            A Y
            C Z
            A Z
            A Z
            B Y
            C Z
            A Z
            C X
            A Y
            C Z
            C Z
            C X
            C X
            C X
            A X
            B Z
            C Z
            C X
            A Y
            A Z
            C Z
            B X
            B Y
            C X
            C Z
            B X
            B Y
            C X
            B X
            C Z
            C X
            C X
            C X
            C X
            A Y
            A Z
            A Y
            B Y
            C Z
            B Y
            B Y
            C Z
            A X
            C Z
            B X
            C Z
            C Z
            A Z
            B Y
            C Z
            C Z
            A Y
            A Z
            A Z
            A Z
            B X
            C X
            C X
            B Y
            C Z
            C X
            B Y
            A Y
            C X
            C Z
            C Z
            C X
            C Y
            A Y
            A Z
            C X
            C X
            A Z
            B X
            C Z
            A X
            C Z
            C X
            C Z
            A X
            A Z
            C X
            B Y
            C Z
            C Z
            B X
            A Y
            B Y
            C Z
            C Z
            A Z
            A Y
            C Z
            C Z
            A X
            B Y
            C Z
            C Z
            B Y
            C X
            C Z
            B X
            B Y
            A Z
            C Z
            C X
            C X
            C Z
            B Z
            B Y
            C Z
            C X
            A Y
            C X
            A Y
            A Z
            B Y
            B X
            C Z
            A Z
            C Z
            C Z
            C Z
            A Y
            B Y
            A Z
            B Y
            C Z
            C X
            B Y
            C Z
            A Y
            C Z
            A Z
            C Z
            C Z
            C Z
            A Z
            C X
            B Y
            C Z
            A Z
            C Z
            C Z
            A Z
            C Z
            C X
            B Z
            C Z
            C Z
            A Z
            C Z
            C Z
            B Y
            B X
            C Z
            C Z
            B Y
            A Y
            C Z
            A Z
            A Z
            C Z
            C X
            C X
            B X
            C X
            A Y
            B X
            A Y
            C Z
            C X
            B Y
            C Z
            C X
            C X
            C X
            B X
            B Z
            C Z
            B Y
            C X
            A Z
            C Z
            C Z
            A Z
            A Z
            C Z
            C Z
            A Z
            A Z
            A Z
            C Z
            A Z
            C Y
            A Z
            C Z
            C Z
            C X
            C X
            C Z
            C Z
            A Z
            C Z
            A Z
            C X
            C X
            C X
            A Y
            A Z
            A Z
            A Y
            B X
            C Z
            C Z
            B X
            C Z
            C X
            B Y
            C Z
            C X
            C X
            B Y
            B Y
            A Y
            A Z
            B X
            C X
            B Y
            B Y
            B Y
            C Z
            C X
            C X
            A Y
            B Z
            A Z
            A Z
            B X
            C X
            A Y
            C X
            C Z
            C X
            A Y
            A Z
            C Z
            A Z
            C Z
            C X
            C X
            A Z
            B X
            B X
            B Y
            C Z
            C Z
            C X
            C X
            C X
            B Y
            C Z
            C X
            B X
            C Z
            C X
            B X
            A Y
            B Y
            C Z
            A Z
            A Y
            C Z
            A Y
            A Y
            C Z
            B Y
            C Z
            B Z
            C Z
            A Z
            C X
            C X
            C Z
            B X
            C X
            B Y
            C Z
            B X
            C Z
            C X
            B X
            B Y
            B Z
            B X
            A Y
            C X
            C Z
            C Z
            A Y
            B X
            A Y
            C X
            C Z
            B Y
            C Z
            C Z
            C Z
            A Z
            A Z
            A Y
            C Z
            B Y
            C Z
            C X
            B Y
            C Z
            C Z
            A X
            C X
            B Y
            A Z
            C Z
            C X
            A Z
            A Y
            C Z
            C Z
            B X
            C Z
            A Z
            A Y
            C X
            A Y
            C Z
            C X
            C X
            C X
            B Y
            C X
            A Y
            C X
            B Y
            B X
            A Y
            B X
            A Y
            B Z
            C Z
            A Z
            B Y
            B X
            C Z
            C Z
            C X
            B Y
            A Z
            A Z
            A Y
            A Y
            C Z
            A Z
            A Z
            B Y
            C X
            C Z
            C Z
            C Z
            A Y
            A Z
            """;
}